# Generated by Django 3.2.20 on 2023-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20230804_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
