# Generated by Django 3.2.20 on 2023-08-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20230809_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.post'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')]),
        ),
    ]
